---

- hosts: all
  gather_facts: true
  tasks:
    - name: Run the specified shell command
      shell: 'uname'
      register: result

    - name: Display the outcome
      debug:
        msg: '{{ result }}'