---
- name: install read-only ssh key
  copy: 
    src: "files/key.pem"
    dest: "{{ ssh_key }}"
    force: yes
    mode: "0600"

- name: Tunnel to server
  command: nohup ssh 

- name: remove read-only ssh key
  file:
    path: "{{ ssh_key }}"
    state: absent